name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
        
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          path: dev
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            main/package-lock.json
            dev/package-lock.json
          
      - name: Build main branch
        run: |
          cd main
          npm ci
          npm run build
          cd ..
        
      - name: Build dev branch
        run: |
          cd dev
          npm ci
          npm run build
          # Rename index.html to dev.html for dev branch
          mv dist/index.html dist/dev.html
          cd ..
        
      - name: Combine builds
        run: |
          # Create final dist directory
          mkdir -p dist
          
          # Copy main build (production)
          cp -r main/dist/* dist/
          
          # Copy dev build file
          cp dev/dist/dev.html dist/
          
          # Copy any assets from dev that might be different
          # but prioritize main assets for production
          for file in dev/dist/*; do
            filename=$(basename "$file")
            if [ "$filename" != "dev.html" ] && [ "$filename" != "index.html" ]; then
              # Only copy if it doesn't exist in main
              if [ ! -f "dist/$filename" ]; then
                cp "$file" dist/
              fi
            fi
          done
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4