name: Build PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install and build
        run: |
          npm ci
          npm run build
        env:
          VITE_BASE: '/gitpocket/'
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ github.event.pull_request.number }}-build
          path: dist/
          retention-days: 7
        
      - name: Comment PR with build status
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            // Check if a build comment already exists
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('PR Build')
            );
            
            const commentBody = `### ✅ PR Build Successful
            
            The PR has been built successfully! 
            
            📦 **[Download Build Artifact](${runUrl})**
            
            To deploy a preview:
            1. Repository maintainers can manually trigger the preview deployment workflow
            2. Or this will be automatically deployed when merged to main
            
            Build details:
            - PR: #${prNumber}
            - Commit: ${context.sha.substring(0, 7)}
            - Workflow: [Run #${context.runNumber}](${runUrl})`;
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            }
